package com.cafe.dto;


// Generated May 15, 2015 1:48:52 PM by Hibernate Tools 4.3.1

/**
 * Staff generated by hbm2java
 */
/**
* Use for full calendar control
*
* @author  	phap.nguyen
* @version 	1.0
* @since   	2015-06-16 
* @update   
*/
@SuppressWarnings("serial")
public class Authority implements java.io.Serializable {
	public final static int HAS_PERMISSION=1;
	public final static int NO_PERMISSION=0;
	public final static int NO_CHECK=2;

	private int view;
	
	private int add;
	
	private int update;
	
	private int delete;
	
	public Authority(){
		view = 1;
		add=1;
		update=1;
		delete=1;
	}
	

	public int getView() {
		return view;
	}

	public void setView(int view) {
		this.view = view;
	}

	public int getAdd() {
		return add;
	}

	public void setAdd(int add) {
		this.add = add;
	}

	public int getUpdate() {
		return update;
	}

	public void setUpdate(int update) {
		this.update = update;
	}

	public int getDelete() {
		return delete;
	}

	public void setDelete(int delete) {
		this.delete = delete;
	}
	
}

