package com.cafe.dto;


// Generated May 15, 2015 1:48:52 PM by Hibernate Tools 4.3.1

/**
 * Staff generated by hbm2java
 */
/**
* Use for full calendar control
*
* @author  	phap.nguyen
* @version 	1.0
* @since   	2015-06-16 
* @update   
*/
public class AutoItem implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = -5688805215553800290L;
	/**
	 * 
	 */
	private String display;
	
	private String title;
	
	private Long sn;
	
	private String description;
	
	private String description2;
	
	private Long value1;
	
	private Long value2;
	
	private String strValue1;
	
	private String strValue2;

	public Long getSn() {
		return sn;
	}

	public void setSn(Long sn) {
		this.sn = sn;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDisplay() {
		return display;
	}

	public void setDisplay(String display) {
		this.display = display;
	}

	public String getDescription2() {
		return description2;
	}

	public void setDescription2(String description2) {
		this.description2 = description2;
	}

	public Long getValue1() {
		return value1;
	}

	public void setValue1(Long value1) {
		this.value1 = value1;
	}

	public Long getValue2() {
		return value2;
	}

	public void setValue2(Long value2) {
		this.value2 = value2;
	}

	public String getStrValue1() {
		return strValue1;
	}

	public void setStrValue1(String strValue1) {
		this.strValue1 = strValue1;
	}

	public String getStrValue2() {
		return strValue2;
	}

	public void setStrValue2(String strValue2) {
		this.strValue2 = strValue2;
	}
}

