package com.cafe.dto;


// Generated May 15, 2015 1:48:52 PM by Hibernate Tools 4.3.1

/**
 * Staff generated by hbm2java
 */
/**
* Use for full calendar control
*
* @author  	phap.nguyen
* @version 	1.0
* @since   	2015-06-16 
* @update   
*/
public class Item implements java.io.Serializable {
	
	public final static int STATISTIC_LIST=1;
	public final static int STATISTIC_FOOD=2;
	public final static int STATISTIC_TABLE=3;
	public final static int STATISTIC_TIME=4;
	public final static int STATISTIC_HOUR=5;
	public final static int STATISTIC_DATE=6;
	public final static int STATISTIC_DAY_OF_WEEK=7;
	public final static int STATISTIC_MONTH=8;
	/**
	 * 
	 */
	private static final long serialVersionUID = -5688805215553800290L;
	/**
	 * 
	 */
	private Long key;
	
	private String name;
	
	public Item(Long key,String name){
		this.key = key;
		this.name=name;
	}

	public Long getKey() {
		return key;
	}

	public void setKey(Long key) {
		this.key = key;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

}

