package com.cafe.dto;

import java.text.MessageFormat;

import com.cafe.entity.Staff;



// Generated May 15, 2015 1:48:52 PM by Hibernate Tools 4.3.1

/**
 * Staff generated by hbm2java
 */
/**
* The login action.
*
* @author  	phap.nguyen
* @version 	1.0
* @since   	2015-05-27 
* @update   
*/
@SuppressWarnings("serial")
public class LoginUser implements java.io.Serializable {
	
	public final static int STS_OK=1;
	public final static int STS_NO_PERMISION=2;
	public final static int STS_FAILURE=0;
	private final static String LOG_INFO_PATTERN="userSn={1}";
	
	private Long sn;
	private String name;
	private Long cafeShopSn;
	private Long roleSn;
	private String userId;
	private int loginStatus = STS_FAILURE;
	private boolean rememberMe;
	private String logInfo;
	public LoginUser() {
		
	}
	
	public LoginUser(Staff staff){
		setStaff(staff);
	}

	
	private void createLogInfo(){
		logInfo=MessageFormat.format(LOG_INFO_PATTERN, new Object[]{sn});
	}
	
	public void setStaff(Staff staff){
		if(null!=staff){
			cafeShopSn = staff.getCafeShopSn();
			sn = staff.getSn();
			name=staff.getName();
			roleSn=staff.getRoleSn();
			userId=staff.getUserId();
			createLogInfo();
		}
	}

	public int getLoginStatus() {
		return loginStatus;
	}

	public void setLoginStatus(int loginStatus) {
		this.loginStatus = loginStatus;
	}

	public Long getSn() {
		return sn;
	}

	public void setSn(Long sn) {
		this.sn = sn;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public Long getRoleSn() {
		return roleSn;
	}

	public void setRoleSn(Long roleSn) {
		this.roleSn = roleSn;
	}

	public boolean isRememberMe() {
		return rememberMe;
	}

	public void setRememberMe(boolean rememberMe) {
		this.rememberMe = rememberMe;
	}

	/**
	 * @return the logInfo
	 */
	public String getLogInfo() {
		return logInfo;
	}

	/**
	 * @param logInfo the logInfo to set
	 */
	public void setLogInfo(String logInfo) {
		this.logInfo = logInfo;
	}

	public Long getCafeShopSn() {
		return cafeShopSn;
	}

	public void setCafeShopSn(Long cafeShopSn) {
		this.cafeShopSn = cafeShopSn;
	}

}
