package com.cafe.dto;

// Generated May 15, 2015 1:48:52 PM by Hibernate Tools 4.3.1

/**
 * Staff generated by hbm2java
 */
/**
* The login action.
*
* @author  	phap.nguyen
* @version 	1.0
* @since   	2015-05-27 
* @update   
*/
@SuppressWarnings("serial")
public class PermissionGroup implements java.io.Serializable {

	private Group food;
	private Group otherOutlay;
	private Group foodUnit;
	private Group cafeOrder;
	private Group permission;
	private Group statistic;
	private Group setting;
	private Group profile;
	private Group table;
	private Group staff;
	
	public void updateToEmpty(){
		if(null==food){
			food = new Group();
		}
		if(null==otherOutlay){
			otherOutlay = new Group();
		}
		if(null==permission){
			permission = new Group();
		}
		if(null==foodUnit){
			foodUnit = new Group();
		}
		if(null==getCafeOrder()){
			setCafeOrder(new Group());
		}
		if(null==statistic){
			statistic = new Group();
		}
		if(null==setting){
			setting = new Group();
		}
		if(null==profile){
			profile = new Group();	
		}
		if(null==table){
			table = new Group();	
		}
		if(null==staff){
			staff = new Group();	
		}
	}
	
	public PermissionGroup(){
		
	}
	
	public Group getPermission() {
		return permission;
	}
	public void setPermission(Group permission) {
		this.permission = permission;
	}
	public Group getSetting() {
		return setting;
	}
	public void setSetting(Group setting) {
		this.setting = setting;
	}
	public Group getProfile() {
		return profile;
	}
	public void setProfile(Group profile) {
		this.profile = profile;
	}

	public Group getFood() {
		return food;
	}

	public void setFood(Group food) {
		this.food = food;
	}

	public Group getOtherOutlay() {
		return otherOutlay;
	}

	public void setOtherOutlay(Group otherOutlay) {
		this.otherOutlay = otherOutlay;
	}

	public Group getFoodUnit() {
		return foodUnit;
	}

	public void setFoodUnit(Group foodUnit) {
		this.foodUnit = foodUnit;
	}

	public Group getStatistic() {
		return statistic;
	}

	public void setStatistic(Group statistic) {
		this.statistic = statistic;
	}

	public Group getCafeOrder() {
		return cafeOrder;
	}

	public void setCafeOrder(Group cafeOrder) {
		this.cafeOrder = cafeOrder;
	}

	public Group getTable() {
		return table;
	}

	public void setTable(Group table) {
		this.table = table;
	}

	public Group getStaff() {
		return staff;
	}

	public void setStaff(Group staff) {
		this.staff = staff;
	}
}
