package com.cafe.dto;

import java.util.List;

import com.cafe.form.CafeOrderForm;
import com.cafe.utils.AppStrUtils;


// Generated May 15, 2015 1:48:52 PM by Hibernate Tools 4.3.1

/**
 * Staff generated by hbm2java
 */
/**
* Use for full calendar control
*
* @author  	phap.nguyen
* @version 	1.0
* @since   	2015-06-16 
* @update   
*/
@SuppressWarnings("serial")
public class PrintOrderDto implements java.io.Serializable {
	private String address = AppStrUtils.EMPTY;
	
	private String address2 = AppStrUtils.EMPTY;
	
	private String email = AppStrUtils.EMPTY;
	
	private String website = AppStrUtils.EMPTY;
	
	private String phone= AppStrUtils.EMPTY;
	
	private String mobile= AppStrUtils.EMPTY;
	
	private String datePrint=AppStrUtils.EMPTY;
	
	private String tableName=AppStrUtils.EMPTY;
	
	private List<CafeOrderForm> cafeOrderList;
	
	private String totalMoney="0";;

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getMobile() {
		return mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getDatePrint() {
		return datePrint;
	}

	public void setDatePrint(String datePrint) {
		this.datePrint = datePrint;
	}

	public String getTableName() {
		return tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	public String getTotalMoney() {
		return totalMoney;
	}

	public void setTotalMoney(String totalMoney) {
		this.totalMoney = totalMoney;
	}

	public List<CafeOrderForm> getCafeOrderList() {
		return cafeOrderList;
	}

	public void setCafeOrderList(List<CafeOrderForm> cafeOrderList) {
		this.cafeOrderList = cafeOrderList;
	}

	public String getAddress2() {
		return address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getWebsite() {
		return website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}
	
}

