package com.cafe.dto;

// Generated May 22, 2015 3:06:46 PM by Hibernate Tools 4.3.1


import com.cafe.utils.AppStrUtils;


/**
 * Role generated by hbm2java
 */
/**
* The login action.
*
* @author  	phap.nguyen
* @version 	1.0
* @since   	2015-11-10 
* @update   
*/
@SuppressWarnings("serial")
public class StatisticByDate implements java.io.Serializable {
	private int numOfFood;
	
	private String dayOfWeek;
	
	private String numOfFoodStr;
	
	private String dateStr;
	
	private int totalMoney;
	
	private String totalMoneyStr;
	
	private String firstOrderTime;
	
	private String lastOrderTime;
	
	public StatisticByDate() {
	}

	public int getNumOfFood() {
		return numOfFood;
	}

	public void setNumOfFood(int numOfFood) {
		this.numOfFood = numOfFood;
		numOfFoodStr = AppStrUtils.priceToString(numOfFood);
	}

	public String getDateStr() {
		return dateStr;
	}

	public void setDateStr(String dateStr) {
		this.dateStr = dateStr;
	}

	public int getTotalMoney() {
		return totalMoney;
	}

	public void setTotalMoney(int totalMoney) {
		this.totalMoney = totalMoney;
		totalMoneyStr = AppStrUtils.priceToString(totalMoney);
	}

	public String getFirstOrderTime() {
		return firstOrderTime;
	}

	public void setFirstOrderTime(String firstOrderTime) {
		this.firstOrderTime = firstOrderTime;
	}

	public String getLastOrderTime() {
		return lastOrderTime;
	}

	public void setLastOrderTime(String lastOrderTime) {
		this.lastOrderTime = lastOrderTime;
	}

	public String getNumOfFoodStr() {
		return numOfFoodStr;
	}

	public void setNumOfFoodStr(String numOfFoodStr) {
		this.numOfFoodStr = numOfFoodStr;
	}

	public String getTotalMoneyStr() {
		return totalMoneyStr;
	}

	public void setTotalMoneyStr(String totalMoneyStr) {
		this.totalMoneyStr = totalMoneyStr;
	}

	public String getDayOfWeek() {
		return dayOfWeek;
	}

	public void setDayOfWeek(String dayOfWeek) {
		this.dayOfWeek = dayOfWeek;
	}
}
