package com.cafe.dto;

// Generated May 22, 2015 3:06:46 PM by Hibernate Tools 4.3.1


import com.cafe.utils.AppStrUtils;


/**
 * Role generated by hbm2java
 */
/**
* The login action.
*
* @author  	phap.nguyen
* @version 	1.0
* @since   	2015-11-10 
* @update   
*/
@SuppressWarnings("serial")
public class StatisticByMonth implements java.io.Serializable {
	private int numOfFood;
	
	private String monthOfYear;
	
	private String numOfFoodStr;
	
	private int totalMoney;
	
	private String totalMoneyStr;
	
	private int moneyPerDay;
	
	private String moneyPerDayStr;
	
	private int totalMoneyOtherOutlay;
	
	private String totalMoneyOtherOutlayStr;
	
	private String timeFrameStart;
	
	private String timeFrameEnd;
	
	public StatisticByMonth() {
	}

	public int getNumOfFood() {
		return numOfFood;
	}

	public void setNumOfFood(int numOfFood) {
		this.numOfFood = numOfFood;
		numOfFoodStr = AppStrUtils.priceToString(numOfFood);
	}

	public int getTotalMoney() {
		return totalMoney;
	}

	public void setTotalMoney(int totalMoney) {
		this.totalMoney = totalMoney;
		totalMoneyStr = AppStrUtils.priceToString(totalMoney);
	}

	public String getNumOfFoodStr() {
		return numOfFoodStr;
	}

	public void setNumOfFoodStr(String numOfFoodStr) {
		this.numOfFoodStr = numOfFoodStr;
	}

	public String getTotalMoneyStr() {
		return totalMoneyStr;
	}

	public void setTotalMoneyStr(String totalMoneyStr) {
		this.totalMoneyStr = totalMoneyStr;
	}

	public String getMonthOfYear() {
		return monthOfYear;
	}

	public void setMonthOfYear(String monthOfYear) {
		this.monthOfYear = monthOfYear;
	}

	public int getTotalMoneyOtherOutlay() {
		return totalMoneyOtherOutlay;
	}

	public void setTotalMoneyOtherOutlay(int totalMoneyOtherOutlay) {
		this.totalMoneyOtherOutlay = totalMoneyOtherOutlay;
		totalMoneyOtherOutlayStr = AppStrUtils.priceToString(totalMoneyOtherOutlay);
	}

	public String getTotalMoneyOtherOutlayStr() {
		return totalMoneyOtherOutlayStr;
	}

	public void setTotalMoneyOtherOutlayStr(String totalMoneyOtherOutlayStr) {
		this.totalMoneyOtherOutlayStr = totalMoneyOtherOutlayStr;
	}

	public String getTimeFrameStart() {
		return timeFrameStart;
	}

	public void setTimeFrameStart(String timeFrameStart) {
		this.timeFrameStart = timeFrameStart;
	}

	public String getTimeFrameEnd() {
		return timeFrameEnd;
	}

	public void setTimeFrameEnd(String timeFrameEnd) {
		this.timeFrameEnd = timeFrameEnd;
	}

	public int getMoneyPerDay() {
		return moneyPerDay;
	}

	public void setMoneyPerDay(int moneyPerDay) {
		this.moneyPerDay = moneyPerDay;
		moneyPerDayStr = AppStrUtils.priceToString(moneyPerDay);
	}

	public String getMoneyPerDayStr() {
		return moneyPerDayStr;
	}

	public void setMoneyPerDayStr(String moneyPerDayStr) {
		this.moneyPerDayStr = moneyPerDayStr;
	}
}
