package com.cafe.dto;

import com.cafe.utils.AppStrUtils;


// Generated May 15, 2015 1:48:52 PM by Hibernate Tools 4.3.1

/**
 * Staff generated by hbm2java
 */
/**
* Use for full calendar control
*
* @author  	phap.nguyen
* @version 	1.0
* @since   	2015-06-16 
* @update   
*/
public class TableStatistic implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = -5688805215553800290L;
	/**
	 * 
	 */
	private Long cafeTableSn;
	
	private int numOfOrder;
	
	private int totalMoney;
	
	private String totalMoneyStr;

	public Long getCafeTableSn() {
		return cafeTableSn;
	}

	public void setCafeTableSn(Long cafeTableSn) {
		this.cafeTableSn = cafeTableSn;
	}

	public int getNumOfOrder() {
		return numOfOrder;
	}

	public void setNumOfOrder(int numOfOrder) {
		this.numOfOrder = numOfOrder;
	}

	public int getTotalMoney() {
		return totalMoney;
	}

	public void setTotalMoney(int totalMoney) {
		this.totalMoney = totalMoney;
		this.setTotalMoneyStr(AppStrUtils.priceToString(this.totalMoney));
	}

	public String getTotalMoneyStr() {
		return totalMoneyStr;
	}

	public void setTotalMoneyStr(String totalMoneyStr) {
		this.totalMoneyStr = totalMoneyStr;
	}
}

