package com.cafe.dto;

import java.util.List;

import com.cafe.utils.AppStrUtils;


// Generated May 15, 2015 1:48:52 PM by Hibernate Tools 4.3.1

/**
 * Staff generated by hbm2java
 */
/**
* Use for full calendar control
*
* @author  	phap.nguyen
* @version 	1.0
* @since   	2015-06-16 
* @update   
*/
@SuppressWarnings("serial")
public class TodayStatistic implements java.io.Serializable {
	
	private List<TableStatistic> tableStatisticList;
	
	private int numOfFoodToday;
	
	private int totalMoneyToday;
	
	private int totalExpectedMoneyToday; 
	
	private String totalExpectedMoneyTodayStr;
	
	private String totalMoneyTodayStr;
	
	private int otherOutlayToday;
	
	private String otherOutlayTodayStr;

	public int getNumOfFoodToday() {
		return numOfFoodToday;
	}

	public void setNumOfFoodToday(int numOfFoodToday) {
		this.numOfFoodToday = numOfFoodToday;
	}

	public int getTotalMoneyToday() {
		return totalMoneyToday;
	}

	public void setTotalMoneyToday(int totalMoneyToday) {
		this.totalMoneyToday = totalMoneyToday;
		this.totalMoneyTodayStr  = AppStrUtils.priceToString(this.totalMoneyToday);
	}

	public List<TableStatistic> getTableStatisticList() {
		return tableStatisticList;
	}

	public void setTableStatisticList(List<TableStatistic> tableStatisticList) {
		this.tableStatisticList = tableStatisticList;
	}

	public int getOtherOutlayToday() {
		return otherOutlayToday;
	}

	public void setOtherOutlayToday(int otherOutlayToday) {
		this.otherOutlayToday = otherOutlayToday;
		this.otherOutlayTodayStr  = AppStrUtils.priceToString(this.otherOutlayToday);
	}

	public String getTotalMoneyTodayStr() {
		return totalMoneyTodayStr;
	}

	public void setTotalMoneyTodayStr(String totalMoneyTodayStr) {
		this.totalMoneyTodayStr = totalMoneyTodayStr;
	}

	public String getOtherOutlayTodayStr() {
		return otherOutlayTodayStr;
	}

	public void setOtherOutlayTodayStr(String otherOutlayTodayStr) {
		this.otherOutlayTodayStr = otherOutlayTodayStr;
	}

	public int getTotalExpectedMoneyToday() {
		return totalExpectedMoneyToday;
	}

	public void setTotalExpectedMoneyToday(int totalExpectedMoneyToday) {
		this.totalExpectedMoneyToday = totalExpectedMoneyToday;
		this.totalExpectedMoneyTodayStr  = AppStrUtils.priceToString(this.totalExpectedMoneyToday);
	}

	public String getTotalExpectedMoneyTodayStr() {
		return totalExpectedMoneyTodayStr;
	}

	public void setTotalExpectedMoneyTodayStr(String totalExpectedMoneyTodayStr) {
		this.totalExpectedMoneyTodayStr = totalExpectedMoneyTodayStr;
	}
}

