package com.cafe.form;

// Generated May 22, 2015 3:06:46 PM by Hibernate Tools 4.3.1

import java.sql.Timestamp;
import java.util.Date;


/**
 * Role generated by hbm2java
 */
/**
* The login action.
*
* @author  	phap.nguyen
* @version 	1.0
* @since   	2015-11-10 
* @update   
*/
@SuppressWarnings("serial")
public class CafeOrderForm implements java.io.Serializable {
	private int orderIdx;
	private Long sn;
	private Long cafeTableSn;
	private String cafeTableName;
	private Long foodSn;
	private String foodName;
	private int price;
	private String priceStr;
	private Date orderTime;
	private String orderDateStr;
	private String orderTimeStr;
	private Date payTime;
	private String payTimeStr;
	private int numOfFood;
	private int status;
	private String memo;
	private Long foodUnitSn;
	private String foodUnitName;
	private int totalMoney;
	private String totalMoneyStr;
	private Timestamp lastUpdate;
	private int inPast;
	private int discount;
	private int numOfPrint;
	private int isDiscount=0;
	
	public CafeOrderForm() {
	}

	public Long getSn() {
		return this.sn;
	}

	public void setSn(Long sn) {
		this.sn = sn;
	}
	
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public Timestamp getLastUpdate() {
		return lastUpdate;
	}

	public void setLastUpdate(Timestamp lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	public int getPrice() {
		return price;
	}

	public void setPrice(int price) {
		this.price = price;
	}

	public Long getFoodUnitSn() {
		return foodUnitSn;
	}

	public void setFoodUnitSn(Long foodUnitSn) {
		this.foodUnitSn = foodUnitSn;
	}

	public Long getFoodSn() {
		return foodSn;
	}

	public void setFoodSn(Long foodSn) {
		this.foodSn = foodSn;
	}

	public int getStatus() {
		return status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public int getTotalMoney() {
		return totalMoney;
	}

	public void setTotalMoney(int totalMoney) {
		this.totalMoney = totalMoney;
	}

	public String getFoodName() {
		return foodName;
	}

	public void setFoodName(String foodName) {
		this.foodName = foodName;
	}

	public String getOrderTimeStr() {
		return orderTimeStr;
	}

	public void setOrderTimeStr(String orderTimeStr) {
		this.orderTimeStr = orderTimeStr;
	}

	public String getPayTimeStr() {
		return payTimeStr;
	}

	public void setPayTimeStr(String payTimeStr) {
		this.payTimeStr = payTimeStr;
	}

	public String getFoodUnitName() {
		return foodUnitName;
	}

	public void setFoodUnitName(String foodUnitName) {
		this.foodUnitName = foodUnitName;
	}

	public Date getOrderTime() {
		return orderTime;
	}

	public void setOrderTime(Date orderTime) {
		this.orderTime = orderTime;
	}

	public Date getPayTime() {
		return payTime;
	}

	public void setPayTime(Date payTime) {
		this.payTime = payTime;
	}

	public Long getCafeTableSn() {
		return cafeTableSn;
	}

	public void setCafeTableSn(Long cafeTableSn) {
		this.cafeTableSn = cafeTableSn;
	}

	public String getCafeTableName() {
		return cafeTableName;
	}

	public void setCafeTableName(String cafeTableName) {
		this.cafeTableName = cafeTableName;
	}

	public int getNumOfFood() {
		return numOfFood;
	}

	public void setNumOfFood(int numOfFood) {
		this.numOfFood = numOfFood;
	}

	public int getOrderIdx() {
		return orderIdx;
	}

	public void setOrderIdx(int orderIdx) {
		this.orderIdx = orderIdx;
	}

	public String getPriceStr() {
		return priceStr;
	}

	public void setPriceStr(String priceStr) {
		this.priceStr = priceStr;
	}

	public String getTotalMoneyStr() {
		return totalMoneyStr;
	}

	public void setTotalMoneyStr(String totalMoneyStr) {
		this.totalMoneyStr = totalMoneyStr;
	}

	public String getOrderDateStr() {
		return orderDateStr;
	}

	public void setOrderDateStr(String orderDateStr) {
		this.orderDateStr = orderDateStr;
	}

	public int getInPast() {
		return inPast;
	}

	public void setInPast(int inPast) {
		this.inPast = inPast;
	}

	public int getDiscount() {
		return discount;
	}

	public void setDiscount(int discount) {
		this.discount = discount;
	}

	public int getNumOfPrint() {
		return numOfPrint;
	}

	public void setNumOfPrint(int numOfPrint) {
		this.numOfPrint = numOfPrint;
	}

	public int getIsDiscount() {
		return isDiscount;
	}

	public void setIsDiscount(int isDiscount) {
		this.isDiscount = isDiscount;
	}
}
