package com.cafe.form;

// Generated May 22, 2015 3:06:46 PM by Hibernate Tools 4.3.1

import java.sql.Timestamp;

import com.cafe.entity.OtherOutlayTran;
import com.cafe.utils.AppDateUtils;
import com.cafe.utils.AppStrUtils;


/**
 * Role generated by hbm2java
 */
/**
* The login action.
*
* @author  	phap.nguyen
* @version 	1.0
* @since   	2015-11-10 
* @update   
*/
@SuppressWarnings("serial")
public class OtherOutlayTranForm implements java.io.Serializable {
	private Long sn;
	private Long cafeShopSn;
	private int totalPrice;
	private String totalPriceStr;
	private Long otherOutlaySn;
	private String otherOutlayName;
	private int numOfOutlay;
	private String memo;
	private String timeTransactionStr;
	private Long createStaffSn;
	private Long lastUpdateStaffSn;
	private Timestamp lastUpdate;
	
	public OtherOutlayTran toOtherOutlayTran(){
		OtherOutlayTran otherOutlayTran = new OtherOutlayTran();
		otherOutlayTran.setSn(sn);
		otherOutlayTran.setCafeShopSn(cafeShopSn);
		otherOutlayTran.setMemo(memo);
		otherOutlayTran.setNumOfOutlay(numOfOutlay);
		otherOutlayTran.setOtherOutlaySn(otherOutlaySn);
		otherOutlayTran.setTotalPrice(totalPrice);
		otherOutlayTran.setTimeTransaction(AppDateUtils.toYYYYMMDDHHMM(timeTransactionStr));
		otherOutlayTran.setCreateStaffSn(createStaffSn);
		otherOutlayTran.setLastUpdateStaffSn(lastUpdateStaffSn);
		return otherOutlayTran;
	}
	
	public void rejectBlank(){
		if(!AppStrUtils.isEmpty(otherOutlayName)){
			otherOutlayName=otherOutlayName.trim();
		}
		if(!AppStrUtils.isEmpty(memo)){
			memo= memo.trim();
		}
	}
	
	public OtherOutlayTranForm() {
	}

	public Long getSn() {
		return this.sn;
	}

	public void setSn(Long sn) {
		this.sn = sn;
	}

	public Timestamp getLastUpdate() {
		return lastUpdate;
	}

	public void setLastUpdate(Timestamp lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	public Long getOtherOutlaySn() {
		return otherOutlaySn;
	}

	public void setOtherOutlaySn(Long otherOutlaySn) {
		this.otherOutlaySn = otherOutlaySn;
	}

	public int getNumOfOutlay() {
		return numOfOutlay;
	}

	public void setNumOfOutlay(int numOfOutlay) {
		this.numOfOutlay = numOfOutlay;
	}

	public String getMemo() {
		return memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public String getOtherOutlayName() {
		return otherOutlayName;
	}

	public void setOtherOutlayName(String otherOutlayName) {
		this.otherOutlayName = otherOutlayName;
	}

	public int getTotalPrice() {
		return totalPrice;
	}

	public void setTotalPrice(int totalPrice) {
		this.totalPrice = totalPrice;
	}

	public String getTimeTransactionStr() {
		return timeTransactionStr;
	}

	public void setTimeTransactionStr(String timeTransactionStr) {
		this.timeTransactionStr = timeTransactionStr;
	}

	public String getTotalPriceStr() {
		return totalPriceStr;
	}

	public void setTotalPriceStr(String totalPriceStr) {
		this.totalPriceStr = totalPriceStr;
	}

	public Long getCreateStaffSn() {
		return createStaffSn;
	}

	public void setCreateStaffSn(Long createStaffSn) {
		this.createStaffSn = createStaffSn;
	}

	public Long getLastUpdateStaffSn() {
		return lastUpdateStaffSn;
	}

	public void setLastUpdateStaffSn(Long lastUpdateStaffSn) {
		this.lastUpdateStaffSn = lastUpdateStaffSn;
	}

	public Long getCafeShopSn() {
		return cafeShopSn;
	}

	public void setCafeShopSn(Long cafeShopSn) {
		this.cafeShopSn = cafeShopSn;
	}
}
