package com.cafe.form;

import java.sql.Timestamp;

import org.apache.commons.lang3.StringUtils;

import com.cafe.entity.Permission;

// Generated May 22, 2015 3:06:46 PM by Hibernate Tools 4.3.1

/**
 * Permission generated by hbm2java
 */
/**
* The login action.
*
* @author  	phap.nguyen
* @version 	1.0
* @since   	2015-07-23 
* @update   
*/
public class PermissionForm implements java.io.Serializable {
	public final static String CHECKED="checked='checked'";
	public final static String CHECKED_VALUE="1";
	public final static String NO_CHECKED_VALUE="0";
	/**
	 * 
	 */
	private static final long serialVersionUID = 2133166800766435794L;
	private Long sn;
	private Long pageGroupSn;
	private String pageGroupName;
	private Long roleSn;
	private String roleName;
	private int view;
	private int modify;
	private int delete;
	private int add;
	private int print;
	
	private String hospitalName;
	
	private int hasView;
	private int hasModify;
	private int hasDelete;
	private int hasCreate;
	private int hasPrint;
	
	private String viewChecked;
	private String modifyChecked;
	private String deleteChecked;
	private String addChecked;
	private String printChecked;
	
	private String viewStr;
	private String modifyStr;
	private String deleteStr;
	private String addStr;
	private String printStr;
	
	
	private Timestamp lastUpdate;
	
	public Permission toPermission(){
		Permission newPermission = new Permission();
		newPermission.setSn(sn);
		newPermission.setPageGroupSn(pageGroupSn);
		newPermission.setRoleSn(roleSn);
		newPermission.setpView(view);
		newPermission.setpAdd(add);
		newPermission.setpModify(modify);
		newPermission.setpDelete(delete);
		return newPermission;
	}
	
	public void updatePermission(){
		if(CHECKED_VALUE.equals(viewStr)){
			view=1;
		}else{
			view=0;
		}
		if(CHECKED_VALUE.equals(addStr)){
			add=1;
		}else{
			add=0;
		}
		if(CHECKED_VALUE.equals(modifyStr)){
			modify=1;
		}else{
			modify=0;
		}
		if(CHECKED_VALUE.equals(deleteStr)){
			delete=1;
		}else{
			delete=0;
		}
		
		if(CHECKED_VALUE.equals(printStr)){
			print=1;
		}else{
			print=0;
		}
		
	}
	
	public PermissionForm(boolean hasPermission) {
		if(false==hasPermission){
			viewChecked = NO_CHECKED_VALUE;
			modifyChecked = NO_CHECKED_VALUE;
			deleteChecked = NO_CHECKED_VALUE;
			addChecked = NO_CHECKED_VALUE;
			printChecked = NO_CHECKED_VALUE;
		}else{
			viewChecked = CHECKED_VALUE;
			modifyChecked = CHECKED_VALUE;
			deleteChecked = CHECKED_VALUE;
			addChecked = CHECKED_VALUE;
			printChecked = CHECKED_VALUE;
		}
		
	}

	public PermissionForm() {
		viewChecked = CHECKED_VALUE;
		modifyChecked = CHECKED_VALUE;
		deleteChecked = CHECKED_VALUE;
		addChecked = CHECKED_VALUE;
		printChecked = CHECKED_VALUE;
	}

	public Long getSn() {
		return this.sn;
	}

	public void setSn(Long sn) {
		this.sn = sn;
	}

	public int getView() {
		return this.view;
	}

	public void setView(int view) {
		this.view = view;
		if(1==view){
			setViewChecked(CHECKED);
			viewStr = CHECKED_VALUE;
		}else{
			setViewChecked(StringUtils.EMPTY);
			viewStr = NO_CHECKED_VALUE;
		}
	}

	public int getModify() {
		return this.modify;
	}

	public void setModify(int modify) {
		this.modify = modify;
		if(1==modify){
			setModifyChecked(CHECKED);
			modifyStr = CHECKED_VALUE;
		}else{
			setModifyChecked(StringUtils.EMPTY);
			modifyStr = NO_CHECKED_VALUE;
		}
	}

	public int getDelete() {
		return this.delete;
	}

	public void setDelete(int delete) {
		this.delete = delete;
		if(1==delete){
			setDeleteChecked(CHECKED);
			deleteStr = CHECKED_VALUE;
		}else{
			setDeleteChecked(StringUtils.EMPTY);
			deleteStr = NO_CHECKED_VALUE;
		}
	}

	public int getAdd() {
		return this.add;
	}

	public void setAdd(int add) {
		this.add = add;
		if(1==add){
			setAddChecked(CHECKED);
			addStr = CHECKED_VALUE;
		}else{
			setAddChecked(StringUtils.EMPTY);
			addStr = NO_CHECKED_VALUE;
		}
	}

	public Long getRoleSn() {
		return roleSn;
	}

	public void setRoleSn(Long roleSn) {
		this.roleSn = roleSn;
	}

	public Timestamp getLastUpdate() {
		return lastUpdate;
	}

	public void setLastUpdate(Timestamp lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	public Long getPageGroupSn() {
		return pageGroupSn;
	}

	public void setPageGroupSn(Long pageGroupSn) {
		this.pageGroupSn = pageGroupSn;
	}

	public String getPageGroupName() {
		return pageGroupName;
	}

	public void setPageGroupName(String pageGroupName) {
		this.pageGroupName = pageGroupName;
	}

	public String getViewChecked() {
		return viewChecked;
	}

	public void setViewChecked(String viewChecked) {
		this.viewChecked = viewChecked;
	}

	public String getModifyChecked() {
		return modifyChecked;
	}

	public void setModifyChecked(String modifyChecked) {
		this.modifyChecked = modifyChecked;
	}

	public String getDeleteChecked() {
		return deleteChecked;
	}

	public void setDeleteChecked(String deleteChecked) {
		this.deleteChecked = deleteChecked;
	}

	public String getAddChecked() {
		return addChecked;
	}

	public void setAddChecked(String addChecked) {
		this.addChecked = addChecked;
	}

	public String getRoleName() {
		return roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public String getViewStr() {
		return viewStr;
	}

	public void setViewStr(String viewStr) {
		this.viewStr = viewStr;
	}

	public String getModifyStr() {
		return modifyStr;
	}

	public void setModifyStr(String modifyStr) {
		this.modifyStr = modifyStr;
	}

	public String getDeleteStr() {
		return deleteStr;
	}

	public void setDeleteStr(String deleteStr) {
		this.deleteStr = deleteStr;
	}

	public String getAddStr() {
		return addStr;
	}

	public void setAddStr(String addStr) {
		this.addStr = addStr;
	}

	public String getHospitalName() {
		return hospitalName;
	}

	public void setHospitalName(String hospitalName) {
		this.hospitalName = hospitalName;
	}

	public int getPrint() {
		return print;
	}

	public void setPrint(int print) {
		this.print = print;
		if(1==print){
			setPrintChecked(CHECKED);
			printStr = CHECKED_VALUE;
		}else{
			setPrintChecked(StringUtils.EMPTY);
			printStr = NO_CHECKED_VALUE;
		}
	}

	public int getHasView() {
		return hasView;
	}

	public void setHasView(int hasView) {
		this.hasView = hasView;
	}

	public int getHasModify() {
		return hasModify;
	}

	public void setHasModify(int hasModify) {
		this.hasModify = hasModify;
	}

	public int getHasDelete() {
		return hasDelete;
	}

	public void setHasDelete(int hasDelete) {
		this.hasDelete = hasDelete;
	}

	public int getHasCreate() {
		return hasCreate;
	}

	public void setHasCreate(int hasCreate) {
		this.hasCreate = hasCreate;
	}

	public int getHasPrint() {
		return hasPrint;
	}

	public void setHasPrint(int hasPrint) {
		this.hasPrint = hasPrint;
	}

	public String getPrintChecked() {
		return printChecked;
	}

	public void setPrintChecked(String printChecked) {
		this.printChecked = printChecked;
	}

	public String getPrintStr() {
		return printStr;
	}

	public void setPrintStr(String printStr) {
		this.printStr = printStr;
	}
}
