package com.cafe.entity;

// Generated May 22, 2015 3:06:46 PM by Hibernate Tools 4.3.1

import java.sql.Timestamp;


/**
 * Role generated by hbm2java
 */
/**
* The login action.
*
* @author  	phap.nguyen
* @version 	1.0
* @since   	2015-11-10 
* @update   
*/
@SuppressWarnings("serial")
public class CafeTable implements java.io.Serializable {
	public final static String DB_SN="SN";
	public final static String DB_CAFE_TABLE_NAME="CAFE_TABLE_NAME";
	public final static String DB_NAME="NAME";
	public final static String DB_LOCATION="LOCATION";
	public final static String DB_TABLE_GROUP_SN="TABLE_GROUP_SN";
	public final static String DB_POSITION="POSITION";
	public final static String DB_LAST_UPDATE="LAST_UPDATE";
	
	public final static String COL_TABLE_GROUP_SN="tableGroupSn";
	public final static String COL_CAFE_SHOP_SN="cafeShopSn";
	
	private Long sn;
	private Long cafeShopSn;
	private String name;
	private String location;
	private int position;
	private Long tableGroupSn;
	private Timestamp lastUpdate;
	
	public CafeTable() {
	}

	public Long getSn() {
		return this.sn;
	}

	public void setSn(Long sn) {
		this.sn = sn;
	}

	public Timestamp getLastUpdate() {
		return lastUpdate;
	}

	public void setLastUpdate(Timestamp lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLocation() {
		return location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public Long getTableGroupSn() {
		return tableGroupSn;
	}

	public void setTableGroupSn(Long tableGroupSn) {
		this.tableGroupSn = tableGroupSn;
	}

	public int getPosition() {
		return position;
	}

	public void setPosition(int position) {
		this.position = position;
	}

	public Long getCafeShopSn() {
		return cafeShopSn;
	}

	public void setCafeShopSn(Long cafeShopSn) {
		this.cafeShopSn = cafeShopSn;
	}
}
