package com.cafe.entity;

// Generated May 22, 2015 3:06:46 PM by Hibernate Tools 4.3.1

import java.sql.Timestamp;
import java.util.Date;


/**
 * Role generated by hbm2java
 */
/**
* The login action.
*
* @author  	phap.nguyen
* @version 	1.0
* @since   	2015-11-10 
* @update   
*/
@SuppressWarnings("serial")
public class CafeOrder implements java.io.Serializable {
	public final static int STATUS_NO_PAY=0;
	public final static int STATUS_ORDER=1;
	public final static int STATUS_PAY=2;
	
	public final static String COL_CAFE_SHOP_SN="cafeShopSn";
	public final static String COL_START_TIME="startTime";
	public final static String COL_END_TIME="endTime";
	public final static String COL_SN="sn";
	public final static String COL_PAY_TIME="payTime";
	public final static String COL_CAFE_TABLE_SN="cafeTableSn";
	public final static String COL_DISCOUNT="discount";
	public final static String COL_LAST_UPDATE_STAFF_SN="lastUpdateStaffSn";
	public final static String COL_NUM_OF_PRINT="numOfPrint";
	
	public final static String DB_SN="SN";
	public final static String DB_CAFE_TABLE_SN="CAFE_TABLE_SN";
	public final static String DB_FOOD_SN="FOOD_SN";
	public final static String DB_PRICE="PRICE";
	public final static String DB_ORDER_TIME="ORDER_TIME";
	public final static String DB_PAY_TIME="PAY_TIME";
	public final static String DB_NUM_OF_FOOD="NUM_OF_FOOD";
	public final static String DB_STATUS="STATUS";
	public final static String DB_MEMO="MEMO";
	public final static String DB_FOOD_UNIT_SN="FOOD_UNIT_SN";
	public final static String DB_TOTAL_MONEY="TOTAL_MONEY";
	public final static String DB_NUM_OF_ORDER="NUM_OF_ORDER";
	public final static String DB_ORDER_DATE="ORDER_DATE";
	public final static String DB_FIRST_ORDER="FIRST_ORDER";
	public final static String DB_LAST_ORDER="LAST_ORDER";
	public final static String DB_DAY_ORDER_NAME="DAY_ORDER_NAME";
	public final static String DB_HOUR_ORDER="HOUR_ORDER";
	public final static String DB_START_TIME="START_TIME";
	public final static String DB_END_TIME="END_TIME";
	public final static String DB_DISCOUNT="DISCOUNT";
	public final static String DB_NUM_OF_PRINT="NUM_OF_PRINT";
	public final static String DB_TOTAL_PROFIT="TOTAL_PROFIT";
	
	private Long sn;
	private Long cafeShopSn;
	private Long cafeTableSn;
	private Long foodSn;
	private int price;
	private Date orderTime;
	private Date payTime;
	private int numOfFood;
	private int status;
	private String memo;
	private Long foodUnitSn;
	private int totalMoney;
	private int totalProfit;
	private int discount;
	private Long createStaffSn;
	private Long lastUpdateStaffSn;
	private int numOfPrint;
	private Timestamp lastUpdate;
	
	public CafeOrder() {
	}

	public Long getSn() {
		return this.sn;
	}

	public void setSn(Long sn) {
		this.sn = sn;
	}
	
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public Timestamp getLastUpdate() {
		return lastUpdate;
	}

	public void setLastUpdate(Timestamp lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	public int getPrice() {
		return price;
	}

	public void setPrice(int price) {
		this.price = price;
	}

	public Long getFoodUnitSn() {
		return foodUnitSn;
	}

	public void setFoodUnitSn(Long foodUnitSn) {
		this.foodUnitSn = foodUnitSn;
	}

	public Long getFoodSn() {
		return foodSn;
	}

	public void setFoodSn(Long foodSn) {
		this.foodSn = foodSn;
	}

	public int getStatus() {
		return status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public int getTotalMoney() {
		return totalMoney;
	}

	public void setTotalMoney(int totalMoney) {
		this.totalMoney = totalMoney;
	}

	public Long getCafeTableSn() {
		return cafeTableSn;
	}

	public void setCafeTableSn(Long cafeTableSn) {
		this.cafeTableSn = cafeTableSn;
	}

	public Date getOrderTime() {
		return orderTime;
	}

	public void setOrderTime(Date orderTime) {
		this.orderTime = orderTime;
	}

	public Date getPayTime() {
		return payTime;
	}

	public void setPayTime(Date payTime) {
		this.payTime = payTime;
	}

	public int getNumOfFood() {
		return numOfFood;
	}

	public void setNumOfFood(int numOfFood) {
		this.numOfFood = numOfFood;
	}

	public int getDiscount() {
		return discount;
	}

	public void setDiscount(int discount) {
		this.discount = discount;
	}

	public Long getCreateStaffSn() {
		return createStaffSn;
	}

	public void setCreateStaffSn(Long createStaffSn) {
		this.createStaffSn = createStaffSn;
	}

	public Long getLastUpdateStaffSn() {
		return lastUpdateStaffSn;
	}

	public void setLastUpdateStaffSn(Long lastUpdateStaffSn) {
		this.lastUpdateStaffSn = lastUpdateStaffSn;
	}

	public int getNumOfPrint() {
		return numOfPrint;
	}

	public void setNumOfPrint(int numOfPrint) {
		this.numOfPrint = numOfPrint;
	}

	public Long getCafeShopSn() {
		return cafeShopSn;
	}

	public void setCafeShopSn(Long cafeShopSn) {
		this.cafeShopSn = cafeShopSn;
	}

	public int getTotalProfit() {
		return totalProfit;
	}

	public void setTotalProfit(int totalProfit) {
		this.totalProfit = totalProfit;
	}
}
