package com.cafe.entity;

// Generated May 15, 2015 1:48:52 PM by Hibernate Tools 4.3.1

import java.sql.Timestamp;

/**
 * Staff generated by hbm2java
 */
/**
* The login action.
*
* @author  	phap.nguyen
* @version 	1.0
* @since   	2015-05-27 
* @update   
*/
@SuppressWarnings("serial")
public class CafeShop implements java.io.Serializable {
	public final static String DB_CAFE_SHOP_NAME="CAFE_SHOP_NAME";
	public final static String DB_CAFE_SHOP_SN="CAFE_SHOP_SN";
	
	private Long sn;
	private String name;
	private String memo;
	private Timestamp lastUpdate;

	public CafeShop() {
	}

	public Long getSn() {
		return this.sn;
	}

	public void setSn(Long sn) {
		this.sn = sn;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getMemo() {
		return memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public Timestamp getLastUpdate() {
		return lastUpdate;
	}

	public void setLastUpdate(Timestamp lastUpdate) {
		this.lastUpdate = lastUpdate;
	}
}
