package com.cafe.entity;

// Generated May 22, 2015 3:06:46 PM by Hibernate Tools 4.3.1

import java.sql.Timestamp;


/**
 * Role generated by hbm2java
 */
/**
* The login action.
*
* @author  	phap.nguyen
* @version 	1.0
* @since   	2015-11-10 
* @update   
*/
@SuppressWarnings("serial")
public class Food implements java.io.Serializable {
	public final static String COL_CAFE_SHOP_SN="cafeShopSn";
	public final static String COL_SN="sn";
	public final static String COL_NAME="name";
	public final static String COL_MEMO="memo";
	public final static String COL_PRICE="price";
	public final static String COL_FOOD_UNIT_SN="foodUnitSn";
	
	public final static String DB_SN="SN";
	public final static String DB_NAME="NAME";
	public final static String DB_FOOD_NAME="FOOD_NAME";
	public final static String DB_MEMO="MEMO";
	public final static String DB_PRICE="PRICE";
	public final static String DB_PROFIT="PROFIT";
	public final static String DB_FOOD_UNIT_SN="FOOD_UNIT_SN";
	public final static String DB_LAST_UPDATE="LAST_UPDATE";
	public final static String DB_FOOD_GROUP_SN="FOOD_GROUP_SN";
	
	private Long sn;
	private Long cafeShopSn;
	private String name;
	private String memo;
	private String recipes;
	private int publicRecipes;
	private int price;
	private int profit;
	private Long foodUnitSn;
	private Long foodGroupSn;
	private Timestamp lastUpdate;
	
	public Food() {
	}

	public Long getSn() {
		return this.sn;
	}

	public void setSn(Long sn) {
		this.sn = sn;
	}
	
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public Timestamp getLastUpdate() {
		return lastUpdate;
	}

	public void setLastUpdate(Timestamp lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getPrice() {
		return price;
	}

	public void setPrice(int price) {
		this.price = price;
	}

	public Long getFoodUnitSn() {
		return foodUnitSn;
	}

	public void setFoodUnitSn(Long foodUnitSn) {
		this.foodUnitSn = foodUnitSn;
	}

	public Long getFoodGroupSn() {
		return foodGroupSn;
	}

	public void setFoodGroupSn(Long foodGroupSn) {
		this.foodGroupSn = foodGroupSn;
	}

	public String getRecipes() {
		return recipes;
	}

	public void setRecipes(String recipes) {
		this.recipes = recipes;
	}

	public int getPublicRecipes() {
		return publicRecipes;
	}

	public void setPublicRecipes(int publicRecipes) {
		this.publicRecipes = publicRecipes;
	}

	public Long getCafeShopSn() {
		return cafeShopSn;
	}

	public void setCafeShopSn(Long cafeShopSn) {
		this.cafeShopSn = cafeShopSn;
	}

	public int getProfit() {
		return profit;
	}

	public void setProfit(int profit) {
		this.profit = profit;
	}
}
