package com.cafe.entity;

// Generated May 22, 2015 3:06:46 PM by Hibernate Tools 4.3.1

import java.sql.Timestamp;

/**
 * Page generated by hbm2java
 */
/**
* The login action.
*
* @author  	phap.nguyen
* @version 	1.0
* @since   	2015-06-30 
* @update   
*/
@SuppressWarnings("serial")
public class PageGroup implements java.io.Serializable {
	
	public final static String CODE_FOOD="food";
	public final static String CODE_CAFE_ORDER="cafeOrder";
	public final static String CODE_PERMISSION="permission";
	public final static String CODE_FOOD_UNIT="foodUnit";
	public final static String CODE_OTHER_OUTLAY="otherOutlay";
	public final static String CODE_STATISTIC="statistic";
	public final static String CODE_SETTING="setting";
	public final static String CODE_PROFILE="profile";
	public final static String CODE_TABLE="table";
	public final static String CODE_STAFF="staff";
	
	public final static int TYPE_HOSPITAL=1;
	public final static int TYPE_SUPADMIN=2;
	public final static int TYPE_ALL=2;
	
	public final static String COL_SN="sn";
	public final static String COL_STATUS="status";
	public final static String COL_TYPE="type";
	public final static String COL_NAME_CODE="nameCode";
	
	public final static String DB_NAME_CODE="NAME_CODE";
	public final static String DB_PAGE_GROUP_NAME="PAGE_GROUP_NAME";
	public final static String DB_HAS_VIEW="HAS_VIEW";
	public final static String DB_HAS_MODIFY="HAS_MODIFY";
	public final static String DB_HAS_CREATE="HAS_CREATE";
	public final static String DB_HAS_DELETE="HAS_DELETE";
	public final static String DB_HAS_PRINT="HAS_PRINT";
	
	private Long sn;
	private String nameCode;
	private String name;
	private String memo;
	private int type;
	private int status;
	private int hasModify;
	private int hasView;
	private int hasDelete;
	private int hasCreate;
	private int hasPrint;
	
	private Timestamp lastUpdate;
	
	
	public Long getSn() {
		return sn;
	}
	public void setSn(Long sn) {
		this.sn = sn;
	}
	
	public String getName(){
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getMemo() {
		return memo;
	}
	public void setMemo(String memo) {
		this.memo = memo;
	}
	public int getType() {
		return type;
	}
	public void setType(int type) {
		this.type = type;
	}
	public int getStatus() {
		return status;
	}
	public void setStatus(int status) {
		this.status = status;
	}
	public Timestamp getLastUpdate() {
		return lastUpdate;
	}
	public void setLastUpdate(Timestamp lastUpdate) {
		this.lastUpdate = lastUpdate;
	}
	public String getNameCode() {
		return nameCode;
	}
	public void setNameCode(String nameCode) {
		this.nameCode = nameCode;
	}
	public int getHasModify() {
		return hasModify;
	}
	public void setHasModify(int hasModify) {
		this.hasModify = hasModify;
	}
	public int getHasView() {
		return hasView;
	}
	public void setHasView(int hasView) {
		this.hasView = hasView;
	}
	public int getHasDelete() {
		return hasDelete;
	}
	public void setHasDelete(int hasDelete) {
		this.hasDelete = hasDelete;
	}
	public int getHasCreate() {
		return hasCreate;
	}
	public void setHasCreate(int hasCreate) {
		this.hasCreate = hasCreate;
	}
	public int getHasPrint() {
		return hasPrint;
	}
	public void setHasPrint(int hasPrint) {
		this.hasPrint = hasPrint;
	}
}
