package com.cafe.entity;

import java.sql.Timestamp;

// Generated May 22, 2015 3:06:46 PM by Hibernate Tools 4.3.1

/**
 * Permission generated by hbm2java
 */
/**
* The login action.
*
* @author  	phap.nguyen
* @version 	1.0
* @since   	2015-05-27 
* @update   
*/
public class Permission implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = -2278097096339460253L;
	
	public final static String COL_P_ADD="add";
	public final static String COL_P_UPDATE="update";
	public final static String COL_P_DELETE="delete";
	public final static String COL_P_VIEW="view";
	public final static String COL_P_LIST="list";
	
	public final static String COL_PAGE_GROUP_SN="pageGroupSn";
	public final static String COL_ROLE_SN="roleSn";
	public final static String COL_TYPE="type";
	public final static String COL_VALUE="value";
	public final static String COL_SN="sn";
	public final static String COL_ADMIN="admin";
	
	public final static String DB_VIEW="P_VIEW";
	public final static String DB_MODIFY="P_MODIFY";
	public final static String DB_DELETE="P_DELETE";
	public final static String DB_ADD="P_ADD";
	public final static String DB_SN="SN";
	public final static String DB_PAGE_GROUP_SN="PAGE_GROUP_SN";
	public final static String DB_ROLE_SN="ROLE_SN";
	public final static String DB_PRINT="P_PRINT";
	
	private Long sn;
	private Long cafeShopSn;
	private Long pageGroupSn; 
	private Long roleSn;
	private int pView;
	private int pModify;
	private int pDelete;
	private int pAdd;
	private int pPrint;
	private Timestamp lastUpdate;

	public Permission() {
	}

	public Long getSn() {
		return this.sn;
	}

	public void setSn(Long sn) {
		this.sn = sn;
	}

	public Long getRoleSn() {
		return roleSn;
	}

	public void setRoleSn(Long roleSn) {
		this.roleSn = roleSn;
	}

	public Timestamp getLastUpdate() {
		return lastUpdate;
	}

	public void setLastUpdate(Timestamp lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	public Long getPageGroupSn() {
		return pageGroupSn;
	}

	public void setPageGroupSn(Long pageGroupSn) {
		this.pageGroupSn = pageGroupSn;
	}

	public int getpView() {
		return pView;
	}

	public void setpView(int pView) {
		this.pView = pView;
	}

	public int getpModify() {
		return pModify;
	}

	public void setpModify(int pModify) {
		this.pModify = pModify;
	}

	public int getpDelete() {
		return pDelete;
	}

	public void setpDelete(int pDelete) {
		this.pDelete = pDelete;
	}

	public int getpAdd() {
		return pAdd;
	}

	public void setpAdd(int pAdd) {
		this.pAdd = pAdd;
	}

	public int getpPrint() {
		return pPrint;
	}

	public void setpPrint(int pPrint) {
		this.pPrint = pPrint;
	}

	public Long getCafeShopSn() {
		return cafeShopSn;
	}

	public void setCafeShopSn(Long cafeShopSn) {
		this.cafeShopSn = cafeShopSn;
	}
}
