package com.cafe.entity;

// Generated May 15, 2015 1:48:52 PM by Hibernate Tools 4.3.1

import java.sql.Timestamp;

/**
 * Staff generated by hbm2java
 */
/**
* The login action.
*
* @author  	phap.nguyen
* @version 	1.0
* @since   	2015-05-27 
* @update   
*/
@SuppressWarnings("serial")
public class Staff implements java.io.Serializable {
	public final static Long ADMIN_SUPER=1L;
	public final static String COL_SN="sn";
	public final static String COL_CAFE_SHOP_SN="cafeShopSn";
	public final static String COL_USER_ID="userId";
	public final static String COL_PASSWORD="password";
	public final static String COL_STATUS="status";
	
	public final static String DB_SN="SN";
	public final static String DB_NAME="NAME";
	public final static String DB_ROLE_SN="ROLE_SN";
	public final static String DB_USER_ID="USER_ID";
	public final static String DB_MEMO="MEMO";
	public final static String DB_LAST_UPDATE="LAST_UPDATE";
	
	private Long sn;
	private Long cafeShopSn;
	private String name;
	private Long roleSn;
	private String memo;
	private String userId;
	private String password;
	private Timestamp lastUpdate;

	public Staff() {
	}

	public Long getSn() {
		return this.sn;
	}

	public void setSn(Long sn) {
		this.sn = sn;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Long getRoleSn() {
		return roleSn;
	}

	public void setRoleSn(Long roleSn) {
		this.roleSn = roleSn;
	}

	public String getMemo() {
		return memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Timestamp getLastUpdate() {
		return lastUpdate;
	}

	public void setLastUpdate(Timestamp lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	public Long getCafeShopSn() {
		return cafeShopSn;
	}

	public void setCafeShopSn(Long cafeShopSn) {
		this.cafeShopSn = cafeShopSn;
	}
}
